[package]
name = "gpg39"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.22"
# clap = "3.2.20"
sequoia-openpgp = { version = "1.10.0", default-features = false, features = ["crypto-nettle"] }
tiny-bip39 = "1.0.0"
zeroize = "1.5.7"
